### ISSUE TITLE
"How to Contribute?" is not documented and has Lorem ipsum as information

### ISSUE THREAD

**Issue by harshita214** [AdobeDocs/dev-site-documentation-template#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

[This](https://adobedocs.github.io/dev-site-documentation-template/support/contribute/) page available on the website does not contain content for "How to Contribute?" instead only Lorem ipsum is written. 

It should be changed to Contributing guidelines.

I am interested to work on this issue. [Here](https://github.com/AdobeDocs/dev-site-documentation-template/blob/main/src/pages/support/contribute/index.md) is the page that is to be edited.

**Comment by timkim** [comment]
Hi that page is just default for authors to add text into and not actually a page on how to contribute.
