### ISSUE TITLE
h4 headings are rendering too close to the preceding content

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeDocs/dev-site-documentation-template#21]
<img width="580" alt="Screen Shot 2020-10-28 at 10 17 07" src="https://user-images.githubusercontent.com/1370591/97448478-13a55580-1907-11eb-9054-713de6a2de3c.png">

Source markdown:
https://github.com/AdobeDocs/uxp-photoshop/blob/main/src/pages/distribution/submission-checklist/index.md

Rendered content:
https://www.adobe.io/photoshop/uxp/distribution/submission-checklist/

**Comment by icaraps** [comment]
Fixed in https://github.com/adobe/gatsby-theme-aio/commit/5d379c0665dd6b9bbb7668bf5c0d45531953f572 and released in @adobe/gatsby-theme-aio@3.1.3 

Please open issues in http://github.com/adobe/gatsby-theme-aio as this is where the code lives. Thanks !
