### ISSUE TITLE
Update .gitignore file for MacOS and common IDEs

### ISSUE THREAD

**Issue by keharper** [AdobeDocs/dev-site-documentation-template#83]
### Expected Behavior

As a Commerce writer, I want to ensure that files generated by MacOS and IDEs commonly used by contributors are not checked into the repo by accident. 

### Actual Behavior

A `.DS_Store` file is checked into the repo for each new file unless I manually prevent it.

### Reproduce Scenario (including but not limited to)

N/A

#### Steps to Reproduce

N/A

#### Platform and Version

MacOS (any)

#### Sample Code that illustrates the problem

N/A

#### Logs taken while reproducing problem

N/A

**Comment by dshevtsov** [comment]
This issue can be closed by #84.
